pipeline {
    agent any
    environment {
        AWS_REGION = "ap-south-1"
        ECR_REPO = "085876626280.dkr.ecr.ap-south-1.amazonaws.com/devops-app"
    }
    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/shuvangipatra/DevopsAssignments.git'
            }
        }
        stage('Login to ECR') {
            steps {
                sh 'aws ecr get-login-password --region ${AWS_REGION} | docker login --username AWS --password-stdin ${ECR_REPO}'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t devops-app eks-project'
                sh 'docker tag devops-app:latest ${ECR_REPO}:${BUILD_NUMBER}'
            }
        }
        stage('Push to ECR') {
            steps {
                sh 'docker push ${ECR_REPO}:${BUILD_NUMBER}'
            }
        }
        stage('Update Manifest') {
            steps {
                sh "sed -i 's|devops-app:.*|devops-app:${BUILD_NUMBER}|g' eks-project/deployment.yaml"
                sh 'git config user.email "shuvangipatra@gmail.com"'
                sh 'git config user.name "shuvangipatra"'
                sh 'git add eks-project/deployment.yaml'
                sh "git commit -m 'Update image tag to ${BUILD_NUMBER}'"
                sh 'git push origin main'
            }
        }
        stage('Apply to Cluster') {
            steps {
                sh 'kubectl apply -f eks-project/deployment.yaml'
                sh 'kubectl apply -f eks-project/service.yaml'
                sh 'kubectl apply -f eks-project/ingress.yaml'
            }
        }
    }
}
