pipeline {
    agent any
    environment {
        AWS_REGION = "ap-south-1"
        ECR_REPO = "085876626280.dkr.ecr.ap-south-1.amazonaws.com/devops-app"
    }
    stages {
        stage('Clone Repo') {
            steps {
                git branch: 'main', url: 'https://github.com/shuvangipatra/DevopsAssignments.git'
            }
        }
        stage('Login to ECR') {
            steps {
                sh '''
                aws ecr get-login-password --region $AWS_REGION | \
                docker login --username AWS --password-stdin $ECR_REPO
                '''
            }
        }
        stage('Build Docker Image') {
            steps {
                sh '''
                docker build -t devops-app eks-project
                docker tag devops-app:latest $ECR_REPO:$BUILD_NUMBER
                '''
            }
        }
        stage('Push to ECR') {
            steps {
                sh 'docker push $ECR_REPO:$BUILD_NUMBER'
            }
        }
        stage('Update Manifest') {
            steps {
                sh '''
                sed -i "s|image:.*|image: $ECR_REPO:$BUILD_NUMBER|g" eks-project/deployment.yaml
                git config user.email "shuvangipatra@gmail.com"
                git config user.name "shuvangipatra"
                git add eks-project/deployment.yaml
                git commit -m "Update image tag to $BUILD_NUMBER"
                git push origin main
                '''
            }
        }
        stage('Apply to Cluster') {
            steps {
                // Checkout eks-manifest repo to get manifests
                git branch: 'main', url: 'https://github.com/shuvangipatra/eks-manifest.git'
                sh '''
                kubectl apply -f deployment.yaml
                kubectl apply -f service.yaml
                kubectl apply -f ingress.yaml
                kubectl rollout status deployment/devops-app
                '''
            }
        }
    }
}
