pipeline {
    agent any
    environment {
        AWS_REGION = "ap-southeast-2"
        ECR_REPO = "512584595883.dkr.ecr.ap-southeast-2.amazonaws.com/eks-lab-project"
        IMAGE_TAG = "latest"
    }
    stages {
        stage('Build Docker Image') {
            steps {
                sh "docker build -t $ECR_REPO:$IMAGE_TAG ."
            }
        }
        stage('Login to ECR') {
            steps {
                sh "aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REPO"
            }
        }
        stage('Push Image to ECR') {
            steps {
                sh "docker push $ECR_REPO:$IMAGE_TAG"
            }
        }
        stage('Update Manifest') {
            steps {
                sh """
                sed -i 's|image:.*|image: $ECR_REPO:$IMAGE_TAG|' deployment.yaml
                git config --global user.email "shuvangipatra@gmail.com"
                git config --global user.name "Shuvangi"
                git add deployment.yaml
                git commit -m 'Update image to $ECR_REPO:$IMAGE_TAG'
                git push origin main
                """
            }
        }
        stage('Deploy to EKS') {
            steps {
                sh "kubectl apply -f deployment.yaml"
                sh "kubectl apply -f service.yaml"
                sh "kubectl apply -f ingress.yaml"
            }
        }
    }
}
